name: build
on:
  workflow_dispatch:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    if: github.repository != 'arkency/nanoc-tailwind-starter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: actions/cache@v3
        with:
          path: |
            output
            tmp
          key: nanoc-${{ github.run_id }}
          restore-keys: |
            nanoc-
      - run: make build
