name: release
on:
  push:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    if: github.repository == "arkency/nanoc-tailwind-starter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          name: release-${{ github.sha }}
          tag_name: version-${{ github.sha }}
          draft: false
          prerelease: false
